export const UserDetailsMapper = {
    'education.schoolName':"School Name",
        'education.schoolLocation': "School Location",
        'education.schoolYearOfPassing':"Year of passing (School)",
        'education.collegeName': "College Name",
        'education.collegeLocation':"College Location",
        'education.collegeStream':"College Stream",
        'education.collegeFieldOfStudy':"Field of Study (College)",
        'education.institutionName':"Institution Name",
        'education.institutionLocation':"Institution Location",
        'education.degree':"Degree",
        'education.discipline':"Discipline",
        'education.institutionYearOfPassing':"Year of Passing (Institution)",
        'firstName':"First Name",
        'lastName': "Last Name",
        'dob': "DOB",
        'fatherName': "Father's Name",
        'motherName': "Mother's Name",
        'adharNumber': "Adhar Number",
        'panNumber':"Pan Number",
        'email':"E-Mail",
        'altEmail':"Alt Email",
        'phoneNumber':"Phone Number",
        'address':"Address",
        "referalCode": "Referal Code",
        "workExperience":"Work Experience"
}
